function myFunction(){
    document.getElementById("name").innerHTML = "MIM";
}


function change(){
    document.getElementById('demo').innerHTML = "Tamima";
}



function myimage() {
    document.getElementById('myimage').src="img/image.jpeg"
   }
 
 function image(){
     document.getElementById('myimage').src="img/Tamima.jpeg"
 }




function fontChange(){
    document.getElementById('font').style.fontSize="35px";
}


function friend(){
    document.getElementById('friend-none').style.display="none"
}


function showtext(){ document.getElementById('show').style.display='block'
}